### ISSUE TITLE
Review Civil War

### ISSUE THREAD

**Issue by Josh16161** [SamLaw2198/the_american_wars#2]
Proof read civil war slides

**Comment by RyanDille** [comment]
Just make these changes to these particular paragraphs, all of these bellow had 1 or 2 simple errors.

The confederate’s navy luck turned after they captured a northern naval base in Virginia. The Merrimack was one of the ships at port when the Confederates took control. In order to outgun the Northern navy, they converted the Merrimack into an ironclad ship and renamed it Virginia. An ironclad ship is a ship with iron on the outside of the hull to prevent damage from cannon fire. 

On the second day, July 2nd, the confederate forces launched an attack on the Union forces that were holding various defensive positions on hills near Gettysburg. This attack gained the Confederates some ground but not enough. On the third on final day of the battle,

July 3rd, General Lee ordered Pickett’s Charge. Pickett’s Charge was a large-scale charge by 12,000 infantrymen straight down the middle of the Union line.
